# Generated by Django 3.0.8 on 2020-08-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoronaStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('continent', models.CharField(default='', max_length=100)),
                ('population', models.IntegerField(default=0)),
                ('total_cases', models.IntegerField(default=0)),
                ('new_cases', models.IntegerField(default=0)),
                ('total_deaths', models.IntegerField(default=0)),
                ('new_deaths', models.IntegerField(default=0)),
                ('total_recovered', models.IntegerField(default=0)),
                ('new_recovered', models.IntegerField(default=0)),
                ('active_cases', models.IntegerField(default=0)),
                ('serious_cases', models.IntegerField(default=0)),
                ('cases_per_million', models.IntegerField(default=0)),
                ('deaths_per_million', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('total_tests', models.IntegerField(default=0)),
                ('tests_per_million', models.IntegerField(default=0)),
                ('who_region', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
