# Generated by Django 3.0.8 on 2020-08-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_world_statistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoronaArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(default='', max_length=5000)),
                ('title', models.CharField(default='', max_length=5000)),
                ('abstract', models.CharField(default='', max_length=5000)),
                ('year', models.IntegerField(default=0)),
                ('journal_publisher', models.CharField(default='', max_length=1000)),
                ('volume', models.CharField(default='', max_length=1000)),
                ('issue', models.CharField(default='', max_length=1000)),
                ('pages', models.CharField(default='', max_length=1000)),
                ('accession_number', models.CharField(default='', max_length=1000)),
                ('doi', models.CharField(default='', max_length=1000)),
                ('url', models.CharField(default='', max_length=1000)),
                ('name_of_database', models.CharField(default='', max_length=1000)),
                ('database_provider', models.CharField(default='', max_length=1000)),
                ('language', models.CharField(default='', max_length=1000)),
                ('keywords', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
